### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by johnsonsirv** [johnsonsirv/weather-today#4]
Kindly add comments and reviews for this app. :sunglasses:

**Comment by shjang7** [comment]
The code is well organized!
For your future project, maybe you could consider a weather forecast app instead of today weather.
Because the open weather API provides us with week information too.

**Comment by grace-mugoiri** [comment]
Good job on the sunglasses app, I can request you make some border radius on the input box for cities(the straight box looks a bit off). Thank you and kudos!
